# Generated by Django 6.1.1 on 2026-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0003_alter_author_name_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
