# Generated by Django 6.1.1 on 2026-09-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0005_publisher_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='established_year',
            field=models.PositiveIntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publisher',
            name='location',
            field=models.CharField(default='Varna', max_length=25),
            preserve_default=False,
        ),
    ]
